apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-secret-es
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: SecretStore
    name: azure-key-vault-secret-store

  target:
    name: keycloak-secret
    creationPolicy: Owner

  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: secret/keycloak-DB-PASSWORD

  - secretKey: ADMIN_USERNAME
    remoteRef:
      key: secret/keycloak-ADMIN-USERNAME

  - secretKey: ADMIN_PASSWORD
    remoteRef:
      key: secret/keycloak-ADMIN-PASSWORD

  - secretKey: CLIENT_WEBAPI_SECRET
    remoteRef:
      key: secret/keycloak-CLIENT-WEBAPI-SECRET

  - secretKey: CDSS_DDSS_CLIENT_SECRET
    remoteRef:
      key: secret/keycloak-CDSS-DDSS-CLIENT-SECRET

  - secretKey: CDSS_HARMONY_CLIENT_SECRET
    remoteRef:
      key: secret/keycloak-CDSS-HARMONY-CLIENT-SECRET

  - secretKey: JOBQUEUE_DDSS_CLIENT_SECRET
    remoteRef:
      key: secret/keycloak-JOBQUEUE-DDSS-CLIENT-SECRET
