apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: octave

resources:
- octave-webapi-deployment.yaml
- octave-webapi-service.yaml
- octave-webapi-ingress.yaml

labels:
  - pairs:
      octave-component: octave-webapi
