apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oct-gitops-ns

resources:
- external-secrets-helm-repo.yaml
- external-secrets-helm-release.yaml

labels:
  - pairs:
      octave-component: infra-external-secrets
