apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: octave

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

labels:
  - pairs:
      octave-component: dotnet-harmony-api-mock
