apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth-secret-es
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: SecretStore
    name: azure-key-vault-secret-store

  target:
    name: oauth2-proxy-secret
    creationPolicy: Owner

  data:
  # octave-demo-temp in Azure App Registrations
  - secretKey: client-id
    remoteRef:
      key: secret/oauth-client-id

  # "AKS octave-temp" in Azure Entra ID
  - secretKey: client-secret
    remoteRef:
      key: secret/oauth-client-secret

  - secretKey: cookie-secret
    remoteRef:
      key: secret/oauth-cookie-secret
