apiVersion: apps/v1
kind: Deployment
metadata:
  name: artemis-nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artemis-nginx-proxy
  template:
    metadata:
      labels:
        app: artemis-nginx-proxy
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8161
        volumeMounts:
        - name: artemis-nginx-proxy-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: artemis-nginx-proxy-config
        configMap:
          name: artemis-nginx-proxy-config
