apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pacs-arc-secret-es
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: SecretStore
    name: azure-key-vault-secret-store

  target:
    name: pacs-arc-secret
    creationPolicy: Owner

  data:
  - secretKey: WILDFLY_ADMIN_USER
    remoteRef:
      key: secret/pacs-arc-WILDFLY-ADMIN-USER

  - secretKey: WILDFLY_ADMIN_PASSWORD
    remoteRef:
      key: secret/pacs-arc-WILDFLY-ADMIN-PASSWORD

  - secretKey: POSTGRES_USER
    remoteRef:
      key: secret/pacs-arc-POSTGRES-USER

  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: secret/pacs-arc-POSTGRES-PASSWORD
