apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- arc-secret-es.yaml
- arc-statefulset.yaml
- arc-service.yaml

# TODO: Move this out to a separate file?
configMapGenerator:
- name: pacs-arc-config
  literals:
  - WILDFLY_CHOWN=/opt/wildfly/standalone /storage
  - WILDFLY_WAIT_FOR=pacs-ldap-service:389 pacs-pg-service:5432
  # From https://github.com/dcm4che-dockerfiles/dcm4chee-arc-psql/blob/master/README.md#environment-variables
  - LDAP_URL=ldap://pacs-ldap-service:389
  - POSTGRES_HOST=pacs-pg-service
  - POSTGRES_DB=pacsdb
