apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pg-secret-es.yaml
  - pg-service.yaml
  - pg-statefulset.yaml

namespace: mynamespace

configMapGenerator:
- name: pacs-pg-config
  literals:
  - PGDATA=/var/lib/postgresql/data/pgdata
