apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pacs-pg-secret-es
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: SecretStore
    name: azure-key-vault-secret-store

  target:
    name: pacs-pg-secret
    creationPolicy: Owner

  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: secret/pacs-pg-POSTGRES-USER

  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: secret/pacs-pg-POSTGRES-PASSWORD
