apiVersion: v1
kind: Service
metadata:
  name: pacs-pg-service
spec:
  selector:
    app: pacs-pg
  ports:
  - protocol: TCP
    port: 5432
    targetPort: pacs-pg-port
  clusterIP: None
  type: ClusterIP
