apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: octave

resources:
- octave-appdata-webapi-deployment.yaml
- octave-appdata-webapi-service.yaml

labels:
  - pairs:
      octave-component: octave-appdata-webapi
