apiVersion: v1
kind: Service
metadata:
  name: octave-pixelsmart-generation-webapi-service
  labels:
    app: octave-pixelsmart-generation-webapi
spec:
  selector:
    app: octave-pixelsmart-generation-webapi
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
