apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- flux-capacitor.yaml
#- namespace.yaml
- external-secrets
- haproxy-ingress
- ama-metrics-settings-configmap.yaml
- container-azm-ms-agentconfig.yaml
