apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- keycloak-mssql-init-db-job.yaml
- keycloak-mssql-secret-es.yaml
- keycloak-mssql-service.yaml
- keycloak-mssql-statefulset.yaml
