apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: acr-helm-charts
  namespace: octave
spec:
  interval: 5m0s
  url: oci://acrdev01global-hudngze7h7hcd6gw.azurecr.io/helm-charts
  type: "oci"
  secretRef:
    name: acrdevglobal-regcred
