apiVersion: v1
kind: Service
metadata:
  name: octave-rdb-webapi-service
  labels:
    app: octave-rdb-webapi
spec:
  selector:
    app: octave-rdb-webapi
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
